apiVersion: v1
kind: Service
metadata:
  name: node-exporter-lb
  namespace: prometheus-node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  type: LoadBalancer 
  
