apiVersion: v1
kind: Service
metadata:
  name: node-exporter-lbs
  namespace: prometheus-node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
  type: LoadBalancer
  
